version: '3.9'

networks:
  app-network:
    driver: bridge

services:
  app:
    networks:
      - app-network
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/Paste
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123


  db:
    networks:
      - app-network
    image: postgres
    environment:
      POSTGRES_DB: "Paste"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "123"
